--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FlynnKunz/GamemodeUI
build-by-default: true
branches:
- main
projects:
  GamemodeUI:
    path: ""
    icon: icon-gm.png
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
    lint:
      phpstan: false
...
