name: GamemodeUI
main: FlynnKunz\GamemodeUI\Main
version: 1.2
api: 4.0.0
authors: [FlynnKunz, fernanACM]
description: "Change gamemode with ui"
website: https://github.com/FlynnKunz/GamemodeUI

commands:
  gamemodeui:
    description: "Open GamemodeUI"
    aliases: [gmui]
    permission: gamemodeui.cmd
   
permissions:
  gamemodeui.cmd:
    description: "Permission To Open GamemodeUI"
    default: op

  gamemodeui.survival:
    description: "Permission To Use Survival Gamemode"
    default: op

  gamemodeui.creative:
    description: "Permission To Use Creative Gamemode"
    default: op
  gamemodeui.adventure:
    description: "Permission To Use Adventure Gamemode"
    default: op
  gamemodeui.spectator:
    description: "Permission To Use Spectator Gamemode"
    default: op
